version: '3'
services:
#  mysql:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: simplon
#    ports:
#      - "33306:33306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  php:
    container_name: "php"
    build:
      context: .docker/php/
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
#    depends_on:
#      - mysql

volumes:
  mysql_data:
